#! /bin/bash
# if there is some issue script will not output required string and 
# udba will show failure
set -e
PACKAGE_NAME=$(echo $1|sed -e 's/udba-//g')
cd /var/tmp/udba-build-root/${PACKAGE_NAME}/
HOME=$(pwd)
mkdir -p rpmdir
mkdir -p srpmdir
mkdir -p /srv/repos/${PACKAGE_NAME}/
UM=$(uname -m)
if [ $UM == "i686" ] ; then
	UM="i586"
fi
export HOME
sh -x fetch.sh
cat << E__O__F > .rpmmacros
%_topdir %(echo "`pwd`")
%_builddir %(echo "`pwd`/builddir")
%_rpmdir %(echo "/srv/repos/${PACKAGE_NAME}")
%_sourcedir %(echo "`pwd`")
%_specdir %(echo "`pwd`")
%_srcrpmdir %(echo "`pwd`/srpmdir")
E__O__F
for rpmspec in *.spec; do
	# nothing smart here really...
	/usr/bin/rpmbuild -ba ${rpmspec}
done
find "/srv/repos/${PACKAGE_NAME}"  -type f -ls
sleep 1
echo "UDBA: Build Complete"
