#! /bin/bash
PACKAGE_NAME=$(echo $1|sed -e 's/udba-//g')
cd /var/tmp/udba-build-root/${PACKAGE_NAME}/
HOME=$(pwd)
mkdir -p rpmdir
mkdir -p srpmdir
mkdir -p /srv/repos/${PACKAGE_NAME}/
UM=$(uname -m)
if [ $UM == "i686" ] ; then
	UM="i586"
fi
export HOME
sh -x fetch.sh
cat << E__O__F > .rpmmacros
%_topdir %(echo "`pwd`")
%_builddir %(echo "`pwd`/builddir")
%_rpmdir %(echo "/srv/repos/${PACKAGE_NAME}")
%_sourcedir %(echo "`pwd`")
%_specdir %(echo "`pwd`")
%_srcrpmdir %(echo "`pwd`/srpmdir")
E__O__F
/usr/bin/rpmbuild -ba *-g*G02.spec
echo "###########################################"
echo "########## First part of build done########"
echo "###########################################"
find "${HOME}/rpmdir/${UM}"  -type f -ls

echo "###########################################"
echo "####### Press enter to continue build #####"
echo "###########################################"

#read pause
/usr/bin/rpmbuild -ba x11-video-*G02.spec
echo "###########################################"
echo "############### All Done ##################"
echo "###########################################"
echo 
echo "Now install files from ${HOME}/rpmdir/${UM}"
echo "Files:"
find "${HOME}/rpmdir/${UM}"  -type f -ls
sleep 10
